version: '3'

services:
  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=forum_django
      - POSTGRES_PASSWORD=forum_django
      - POSTGRES_DB=forum_django_db
volumes:
  postgres_data: